# Generated by Django 4.1.2 on 2022-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0003_alter_doctor_speciality_patientconsultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="charge",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
