# Generated by Django 4.1.2 on 2022-11-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0004_patientconsultation_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoravailability",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability",
                to="details.doctor",
            ),
        ),
    ]
