# Generated by Django 4.1.2 on 2022-11-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0005_alter_doctoravailability_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="duration",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
