# Generated by Django 4.1.2 on 2022-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0006_patientconsultation_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientconsultation",
            name="time",
            field=models.TimeField(default=None),
        ),
    ]
