# Generated by Django 4.1.2 on 2022-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0007_patientconsultation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientconsultation",
            name="charge",
        ),
        migrations.AddField(
            model_name="doctor",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="certificate",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="doctor",
            name="charge",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="profile_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
