# Generated by Django 4.1.2 on 2022-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
